import type { BrandId } from './brand';
import type { Entity, Id, ISODateString } from './common';
import type { ProductId } from './product';

export type OfferId = Id<'offer'>;

export type OfferKind = 'coupon' | 'bank-offer' | 'price-drop' | 'bundle' | 'exchange';

export interface Offer extends Entity<'offer'> {
  readonly id: OfferId;
  readonly kind: OfferKind;
  readonly retailer: string;
  readonly description: string;
  readonly discountPercent?: number;
  readonly flatDiscount?: number;
  readonly code?: string;
  readonly brandId?: BrandId;
  readonly productIds: readonly ProductId[];
  readonly startsAt: ISODateString;
  readonly expiresAt: ISODateString;
  /** The plain retailer product URL, exactly as copied from the retailer's
   *  own site — no tracking parameters, nothing generated by hand. It is
   *  converted into a tracked affiliate link automatically while the page is
   *  built (see `lib/affiliate/resolve.ts`), which is why adding a product
   *  needs no manual link-conversion step. Prefer this over `buyUrl`. */
  readonly retailerUrl?: string;
  /** The tracked destination a shopper actually lands on. Normally you do not
   *  set this by hand: it is filled in at build time from `retailerUrl`. Set
   *  it directly only for a link generated somewhere other than Cuelinks (the
   *  EarnKaro links predate the API integration), or as the fallback used
   *  when automatic conversion cannot reach the API. `OfferCard` renders its
   *  external "Buy at ..." link only when this ends up present. */
  readonly buyUrl?: string;
}
